from django.db import models


class Game(models.Model):
    id = models.BigAutoField(primary_key=True)
    team_home = models.ForeignKey('Team', db_column='team_home', blank=True, null=True, related_name='games_at_home', on_delete=models.CASCADE)
    team_home_goals = models.BigIntegerField(blank=True, null=True)
    team_away = models.ForeignKey('Team', db_column='team_away', blank=True, null=True, related_name='games_at_away', on_delete=models.CASCADE)
    team_away_goals = models.BigIntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.team_home}, {self.team_home_goals}, {self.team_away}, {self.team_away_goals}"

    class Meta:
        db_table = 'games'

# Generated by: ./manage.py inspectdb
# class Games(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     team_home = models.ForeignKey('Teams', models.DO_NOTHING, db_column='team_home', blank=True, null=True)
#     team_home_goals = models.BigIntegerField(blank=True, null=True)
#     team_away = models.ForeignKey('Teams', models.DO_NOTHING, db_column='team_away', blank=True, null=True)
#     team_away_goals = models.BigIntegerField(blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'games'


class Team(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    points = models.BigIntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.id}, {self.name}, {self.points}"

    class Meta:
        db_table = 'teams'


# Generated by: ./manage.py inspectdb
# class Teams(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     name = models.TextField()
#     points = models.BigIntegerField(blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'teams'
