# Generated by Django 2.2.7 on 2019-12-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('points', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_home_goals', models.BigIntegerField(blank=True, null=True)),
                ('team_away_goals', models.BigIntegerField(blank=True, null=True)),
                ('team_away', models.ForeignKey(blank=True, db_column='team_away', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_at_away', to='football.Team')),
                ('team_home', models.ForeignKey(blank=True, db_column='team_home', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_at_home', to='football.Team')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
